% Добавляет цифру в названии файлов. Например 'Px.dat' в 'Px1.dat' 
% ver 5.1
%19.03.2017

n = 2;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

norm_length = dlmread  ('dim_value.dat');
dim_char    = fileread ('dim_name.dat');
fre     = dlmread ('fre.dat');
H       = dlmread ('H.dat');
Px      = dlmread ('Px.dat');
Py      = dlmread ('Py.dat');
Pz      = dlmread ('Pz.dat');
Tx      = dlmread ('Tx.dat');
Ty      = dlmread ('Ty.dat');
Tz      = dlmread ('Tz.dat');
mx      = dlmread ('mx.dat');
my      = dlmread ('my.dat');
mz      = dlmread ('mz.dat');
Mxx     = dlmread ('Mxx.dat');
Mxy     = dlmread ('Mxy.dat');
Mxz     = dlmread ('Mxz.dat');
Myx     = dlmread ('Myx.dat');
Myy     = dlmread ('Myy.dat');
Myz     = dlmread ('Myz.dat');
Mzx     = dlmread ('Mzx.dat');
Mzy     = dlmread ('Mzy.dat');
Mzz     = dlmread ('Mzz.dat');
Qxx     = dlmread ('Qxx.dat');
Qyy     = dlmread ('Qyy.dat');
Qzz     = dlmread ('Qzz.dat');
Qxy     = dlmread ('Qxy.dat');
Qxz     = dlmread ('Qxz.dat');
Qyx     = dlmread ('Qyx.dat');
Qyz     = dlmread ('Qyz.dat');
Qzx     = dlmread ('Qzx.dat');
Qzy     = dlmread ('Qzy.dat');
Oxxx    = dlmread ('Oxxx.dat');
Oxxy    = dlmread ('Oxxy.dat');
Oxxz    = dlmread ('Oxxz.dat');
Oyyx    = dlmread ('Oyyx.dat');
Oyyy    = dlmread ('Oyyy.dat');
Oyyz    = dlmread ('Oyyz.dat');
Ozzx    = dlmread ('Ozzx.dat');
Ozzy    = dlmread ('Ozzy.dat');
Ozzz    = dlmread ('Ozzz.dat');
Oxyz    = dlmread ('Oxyz.dat');
Lambdax = dlmread ('Lambdax.dat');
Lambday = dlmread ('Lambday.dat');
Lambdaz = dlmread ('Lambdaz.dat');
absCS   = dlmread ('absCS.dat');
scat    = dlmread ('scat.dat');
ForScat           = dlmread ('ForScat.dat');
BackScat          = dlmread ('BackScat.dat');
ForScatPoint      = dlmread ('ForScatPoint.dat');
BackScatPoint     = dlmread ('BackScatPoint.dat');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

dlmwrite (strcat('dim_value', num2str(n), '.dat'), norm_length, 'delimiter', '\t');
filewrite (strcat('dim_name', num2str(n), '.dat'), dim_char);
dlmwrite (strcat('fre', num2str(n), '.dat'), fre, 'delimiter', '\t');
dlmwrite (strcat('H', num2str(n), '.dat'), H, 'delimiter', '\t');
dlmwrite (strcat('Px', num2str(n), '.dat'), Px, 'delimiter', '\t');
dlmwrite (strcat('Py', num2str(n), '.dat'), Py, 'delimiter', '\t');
dlmwrite (strcat('Pz', num2str(n), '.dat'), Pz, 'delimiter', '\t');
dlmwrite (strcat('Tx', num2str(n), '.dat'), Tx, 'delimiter', '\t');
dlmwrite (strcat('Ty', num2str(n), '.dat'), Ty, 'delimiter', '\t');
dlmwrite (strcat('Tz', num2str(n), '.dat'), Tz, 'delimiter', '\t');
dlmwrite (strcat('mx', num2str(n), '.dat'), mx, 'delimiter', '\t');
dlmwrite (strcat('my', num2str(n), '.dat'), my, 'delimiter', '\t');
dlmwrite (strcat('mz', num2str(n), '.dat'), mz, 'delimiter', '\t');
dlmwrite (strcat('Mxx', num2str(n), '.dat'), Mxx, 'delimiter', '\t');
dlmwrite (strcat('Mxy', num2str(n), '.dat'), Mxy, 'delimiter', '\t');
dlmwrite (strcat('Mxz', num2str(n), '.dat'), Mxz, 'delimiter', '\t');
dlmwrite (strcat('Myx', num2str(n), '.dat'), Myx, 'delimiter', '\t');
dlmwrite (strcat('Myy', num2str(n), '.dat'), Myy, 'delimiter', '\t');
dlmwrite (strcat('Myz', num2str(n), '.dat'), Myz, 'delimiter', '\t');
dlmwrite (strcat('Mzx', num2str(n), '.dat'), Mzx, 'delimiter', '\t');
dlmwrite (strcat('Mzy', num2str(n), '.dat'), Mzy, 'delimiter', '\t');
dlmwrite (strcat('Mzz', num2str(n), '.dat'), Mzz, 'delimiter', '\t');
dlmwrite (strcat('Qxx', num2str(n), '.dat'), Qxx, 'delimiter', '\t');
dlmwrite (strcat('Qyy', num2str(n), '.dat'), Qyy, 'delimiter', '\t');
dlmwrite (strcat('Qzz', num2str(n), '.dat'), Qzz, 'delimiter', '\t');
dlmwrite (strcat('Qxy', num2str(n), '.dat'), Qxy, 'delimiter', '\t');
dlmwrite (strcat('Qxz', num2str(n), '.dat'), Qxz, 'delimiter', '\t');
dlmwrite (strcat('Qyx', num2str(n), '.dat'), Qyx, 'delimiter', '\t');
dlmwrite (strcat('Qyz', num2str(n), '.dat'), Qyz, 'delimiter', '\t');
dlmwrite (strcat('Qzx', num2str(n), '.dat'), Qzx, 'delimiter', '\t');
dlmwrite (strcat('Qzy', num2str(n), '.dat'), Qzy, 'delimiter', '\t');
dlmwrite (strcat('Oxxx', num2str(n), '.dat'), Oxxx, 'delimiter', '\t');
dlmwrite (strcat('Oxxy', num2str(n), '.dat'), Oxxy, 'delimiter', '\t');
dlmwrite (strcat('Oxxz', num2str(n), '.dat'), Oxxz, 'delimiter', '\t');
dlmwrite (strcat('Oyyx', num2str(n), '.dat'), Oyyx, 'delimiter', '\t');
dlmwrite (strcat('Oyyy', num2str(n), '.dat'), Oyyy, 'delimiter', '\t');
dlmwrite (strcat('Oyyz', num2str(n), '.dat'), Oyyz, 'delimiter', '\t');
dlmwrite (strcat('Ozzx', num2str(n), '.dat'), Ozzx, 'delimiter', '\t');
dlmwrite (strcat('Ozzy', num2str(n), '.dat'), Ozzy, 'delimiter', '\t');
dlmwrite (strcat('Ozzz', num2str(n), '.dat'), Ozzz, 'delimiter', '\t');
dlmwrite (strcat('Oxyz', num2str(n), '.dat'), Oxyz, 'delimiter', '\t');
dlmwrite (strcat('Lambdax', num2str(n), '.dat'), Lambdax, 'delimiter', '\t');
dlmwrite (strcat('Lambday', num2str(n), '.dat'), Lambday, 'delimiter', '\t');
dlmwrite (strcat('Lambdaz', num2str(n), '.dat'), Lambdaz, 'delimiter', '\t');
dlmwrite (strcat('absCS', num2str(n), '.dat'), absCS, 'delimiter', '\t');
dlmwrite (strcat('scat', num2str(n), '.dat'), scat, 'delimiter', '\t');
dlmwrite (strcat('ForScat', num2str(n), '.dat'), ForScat, 'delimiter', '\t');
dlmwrite (strcat('BackScat', num2str(n), '.dat'), BackScat, 'delimiter', '\t');
dlmwrite (strcat('ForScatPoint', num2str(n), '.dat'), ForScatPoint, 'delimiter', '\t');
dlmwrite (strcat('BackScatPoint', num2str(n), '.dat'), BackScatPoint, 'delimiter', '\t');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

delete ('fre.dat');
delete ('H.dat');
delete ('Px.dat');
delete ('Py.dat');
delete ('Pz.dat');
delete ('Tx.dat');
delete ('Ty.dat');
delete ('Tz.dat');
delete ('mx.dat');
delete ('my.dat');
delete ('mz.dat');
delete ('Mxx.dat');
delete ('Mxy.dat');
delete ('Mxz.dat');
delete ('Myx.dat');
delete ('Myy.dat');
delete ('Myz.dat');
delete ('Mzx.dat');
delete ('Mzy.dat');
delete ('Mzz.dat');
delete ('Qxx.dat');
delete ('Qyy.dat');
delete ('Qzz.dat');
delete ('Qxy.dat');
delete ('Qxz.dat');
delete ('Qyx.dat');
delete ('Qyz.dat');
delete ('Qzx.dat');
delete ('Qzy.dat');
delete ('Oxxx.dat');
delete ('Oxxy.dat');
delete ('Oxxz.dat');
delete ('Oyyx.dat');
delete ('Oyyy.dat');
delete ('Oyyz.dat');
delete ('Ozzx.dat');
delete ('Ozzy.dat');
delete ('Ozzz.dat');
delete ('Oxyz.dat');
delete ('Lambdax.dat');
delete ('Lambday.dat');
delete ('Lambdaz.dat');
delete ('absCS.dat');
delete ('scat.dat');
delete ('ForScat.dat');
delete ('BackScat.dat');
delete ('ForScatPoint.dat');
delete ('BackScatPoint.dat');